name: bfnlibrary
description: BFN Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.0
  cloud_firestore: ^0.14.0+2
  intl: ^0.16.1
  shared_preferences: ^0.5.10
  dynamic_theme: 1.0.1
  flutter_dotenv: ^2.1.0
  google_fonts: ^1.1.0
  getflutter: ^1.1.3
  google_sign_in: ^4.5.3
  provider: ^4.3.2+1
  dots_indicator: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

