name: bfnlibrary
description: BFN Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  google_fonts: ^1.1.1
  getflutter: ^1.1.3
  google_sign_in: ^4.5.5
  provider: ^4.3.2+2
  dots_indicator: ^1.2.0
  font_awesome_flutter: ^8.10.0
  cupertino_icons: ^1.0.0
  stellar_flutter_sdk: ^1.1.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  cloud_firestore:
  http: ^0.12.2
  page_transition: ^1.1.7+2
  flutter_dotenv: ^2.1.0
  introduction_screen: ^1.0.9

#  cloud_firestore: ^0.14.1+2
  intl: ^0.16.1
  shared_preferences: ^0.5.12+2
  dynamic_theme: 1.0.1

  responsive_builder:
  syncfusion_flutter_datepicker: ^18.3.40-beta
  json_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here
  build_runner:
  json_serializable:

