name: bfnlibrary
description: BFN Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  google_fonts: ^1.1.0
  getflutter: ^1.1.3
  google_sign_in: ^4.5.4
  provider: ^4.3.2+2
  dots_indicator: ^1.2.0

  cupertino_icons: ^1.0.0
  stellar_flutter_sdk: ^1.0.7
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  firebase_messaging: ^7.0.2
  firebase_storage: ^4.0.1
  http: ^0.12.2
  page_transition: ^1.1.7+2
  flutter_dotenv: ^2.1.0
  introduction_screen: ^1.0.9

  cloud_firestore: ^0.14.1+2
  intl: ^0.16.1
  shared_preferences: ^0.5.12
  dynamic_theme: 1.0.1

  responsive_builder:


dev_dependencies:
  flutter_test:
    sdk: flutter

